### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/me-parissa#13]
https://www.w3schools.com/css/css3_colors.asp

**Comment by Parissa-Parsania** [comment]
Summary:

- RGBA Colors:
consist of 4 numbers; rgba(red, green, blue, alpha). The alpha parameter is a number between 0.0 (fully transparent) and 1.0 (fully opaque).
example: 
`background-color: rgba(255, 0, 0, 0.3);`  will be red with opacity. (the first number is red, the second is green, the third is blue and the last one indicated the opacity)

- HSL Colors:
hsl(hue, saturation, lightness).

*Hue is a degree on the color wheel (from 0 to 360):
0 (or 360) is red
120 is green
240 is blue
*Saturation is a percentage value: 100% is the full color.
*Lightness is also a percentage; 0% is dark (black) and 100% is white.
example: 
`background-color: hsl(120, 100%, 50%) `is green.
`background-color: hsl(120, 100%, 75%)` is light green

- HSLA Colors:
HSLA color values are an extension of HSL color values with an alpha channel - which specifies the opacity for a color.

An HSLA color value is specified with: hsla(hue, saturation, lightness, alpha), where the alpha parameter defines the opacity. The alpha parameter is a number between 0.0 (fully transparent) and 1.0 (fully opaque).
example: 
`background-color: hsla(120, 100%, 50%, 0.3)` is green with opacity.
`background-color: hsla(120, 100%, 25%, 0.3)` is dark green with opacity

- Opacity:
The CSS opacity property sets the opacity for the whole element (both background color and text will be opaque/transparent).

The opacity property value must be a number between 0.0 (fully transparent) and 1.0 (fully opaque).
example: 
`background-color:rgb(255,0,0);opacity:0.6;` is red with opacity
