### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/me-parissa#16]
https://www.w3schools.com/css/css_icons.asp

**Comment by Parissa-Parsania** [comment]
summary:

1. Font Awesome Icons:

- This is my kit code that needs to be added in `Head`:
<script src="https://kit.fontawesome.com/832571b038.js" ></script>

-  every icons has its own special code that will be copied from the website into `body`:
for example: <i class="fab fa-acquisitions-incorporated fa-5x"></i>

- The fa-xs, fa-sm, fa-lg, fa-2x, fa-3x, fa-4x, fa-5x, fa-6x, fa-7x, fa-8x, fa-9x, or fa-10x classes are used to adjust the icon sizes relative to their container.

2. Bootstrap Icons:

- Copy-paste the stylesheet <link> into your <head> before all other stylesheets to load our CSS.
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 

- find the icon you want in Bootstrap website and copy the HTML in `body`

- to make the icon smaller or bigger, give the HTML element `Style`
style="font-size: x-large

3.Google Icons:

- To use the Google icons, add the following line inside the <head> section of your HTML page:

<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

- examples of icons:
<i class="material-icons">cloud</i>
<i class="material-icons">favorite</i>
<i class="material-icons">attachment</i>
<i class="material-icons">computer</i>
<i class="material-icons">traffic</i>

**Comment by Parissa-Parsania** [comment]
@arashbahreini 
Thank you Arash for the great assignment you gave me. I created my own kit code on Font Awesome website, and I tried some icons on an HTML test page.
Now I am more familiar with bootstrap as well, but I found google icons a bit confusing, so it would be nice to check that together.
