### ISSUE TITLE
Overflow

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/me-parissa#18]
https://www.w3schools.com/css/css_overflow.asp

**Comment by Parissa-Parsania** [comment]
Summary:
CSS Layout - Overflow:

- The CSS overflow property controls what happens to content that is too big to fit into an area.

- The overflow property specifies whether to clip the content or to add scrollbars when the content of an element is too big to fit in the specified area.
 It only works for block elements with a specified height.

- The overflow property has the following values:

*visible - Default. The overflow is not clipped. The content renders outside the element's box
*hidden - The overflow is clipped, and the rest of the content will be invisible
*scroll - The overflow is clipped, and a scrollbar is added to see the rest of the content
Note that this will add a scrollbar both horizontally and vertically (even if you do not need it)
*auto - Similar to scroll, but it adds scrollbars only when necessary

- overflow-x and overflow-y
 specifies whether to change the overflow of content just horizontally or vertically (or both):

overflow-x specifies what to do with the left/right edges of the content.
overflow-y specifies what to do with the top/bottom edges of the content.
