### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/me-parissa#26]
https://www.w3schools.com/css/css3_images.asp

**Comment by Parissa-Parsania** [comment]
Learn how to style images using CSS:

- Rounded Images

- Thumbnail Images

- Responsive Images(automatically adjust to fit the size of the screen)

- Center an Image

- Polaroid Images / Cards

- Transparent Image

- Image Text (How to position text in an image)

- Image Filters

- Image Hover Overlay (Create an overlay effect on hover)

- Flip an Image

- Responsive Image Gallery (opens onclick in a black screen)

- Image Modal (Advanced) (opens in a darker screen in the same page with X button to close)

**Comment by Parissa-Parsania** [comment]
@arashbahreini :
I finished studying CSS styling images. but there are some parts that need to be discussed.
