### ISSUE TITLE
JavaScript Events

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/me-parissa#30]
https://www.w3schools.com/js/js_events.asp

**Comment by Parissa-Parsania** [comment]
Common HTML Events:

- onchange: An HTML element has been changed

- onclick : The user clicks an HTML element

- onmouseover : The user moves the mouse over an HTML element

- onmouseout : The user moves the mouse away from an HTML element

- onkeydown : The user pushes a keyboard key

- onload : The browser has finished loading the page
