### ISSUE TITLE
JavaScript Number Methods

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/me-parissa#34]
https://www.w3schools.com/js/js_number_methods.asp

**Comment by Parissa-Parsania** [comment]
1. Number Methods and Properties:

- The toString() Method: returns a number as a string

- The toExponential() Method: returns a string, with a number rounded and written using exponential notation.

- The toFixed() Method: returns a string, with the number written with a specified number of decimals.
perfect for working with money

- The toPrecision() Method: returns a string, with a number written with a specified length

- The valueOf() Method: returns a number as a number

2.Converting Variables to Numbers:

- Number() :Returns a number, converted from its argument

- parseFloat() : Parses its argument and returns a floating-point number-parses a string and returns a number. Spaces are allowed. Only the first number is returned

- parseInt() : Parses its argument and returns an integer- parses a string and returns a whole number. Spaces are allowed. Only the first number is returned

3.Number Properties:

- MAX_VALUE : Returns the largest number possible in JavaScript

- MIN_VALUE : Returns the smallest number possible in JavaScript

- POSITIVE_INFINITY : Represents infinity (returned on overflow)

- NEGATIVE_INFINITY : Represents negative infinity (returned on overflow)

- NaN :Represents a "Not-a-Number" value

**Comment by Parissa-Parsania** [comment]
@arashbahreini :
 I read the link you shared in this task and wrote a summary in comments but I think it's better to review that together as it is not that much clear in some parts.
Thanks in advance
