### ISSUE TITLE
JavaScript Arrays

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/me-parissa#35]
https://www.w3schools.com/js/js_arrays.asp

**Comment by Parissa-Parsania** [comment]
Summary:

- JavaScript arrays are used to store multiple values in a single variable.

- What is an Array?

- Creating an Array

- Using the JavaScript Keyword new

- Access the Elements of an Array

- Changing an Array Element

- Access the Full Array

- Arrays are Objects

- Array Elements Can Be Objects

- Array Properties and Methods

- The length Property

- Accessing the First Array Element
fruits = ["Banana", "Orange", "Apple", "Mango"];
var first = fruits[0];
- Accessing the Last Array Element
fruits = ["Banana", "Orange", "Apple", "Mango"];
var last = fruits[fruits.length - 1];

- Looping Array Elements

- Adding Array Elements: `push() `method

- Associative Arrays

- The Difference Between Arrays and Objects

- When to Use Arrays. When to use Objects:
JavaScript does not support associative arrays.
You should use objects when you want the element names to be strings (text).
You should use arrays when you want the element names to be numbers.

- Avoid new Array()

- How to Recognize an Array

**Comment by Parissa-Parsania** [comment]
@arashbahreini 
There are 2 topics from Arrays that need clarification:
- Looping Array Elements (+examples)
- How to recognize an Array? (the question is that why do we need to recognize an Array?)
