### ISSUE TITLE
JavaScript if else and else if

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/me-parissa#44]
https://www.w3schools.com/js/js_if_else.asp

**Comment by Parissa-Parsania** [comment]
Summary:

- Conditional Statements: are used to perform different actions based on different conditions.
Use` if` to specify a block of code to be executed, if a specified condition is true
Use `else` to specify a block of code to be executed, if the same condition is false
Use `else if `to specify a new condition to test, if the first condition is false
Use` switch` to specify many alternative blocks of code to be executed

Syntax:
```
if (condition1) {
  //  block of code to be executed if condition1 is true
} else if (condition2) {
  //  block of code to be executed if the condition1 is false and condition2 is true
} else {
  //  block of code to be executed if the condition1 is false and condition2 is false
}
```
