### ISSUE TITLE
JavaScript Switch Statement

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/me-parissa#45]
https://www.w3schools.com/js/js_switch.asp

**Comment by Parissa-Parsania** [comment]
Summary:

- The `switch` statement is used to perform different actions based on different conditions. to select one of many code blocks to be executed.

Syntax
```
switch(expression) {
  case x:
    // code block
    break;
  case y:
    // code block
    break;
  default:
    // code block
}
```
This is how it works:

The switch expression is evaluated once.
The value of the expression is compared with the values of each case.
If there is a match, the associated block of code is executed.
If there is no match, the default code block is executed.

- The `break `Keyword
When JavaScript reaches a `break` keyword, it breaks out of the `switch `block.

- The `default `Keyword
The `default` keyword specifies the code to run if there is no case match

- Common Code Blocks:
Sometimes you will want different switch cases to use the same code.
In this example case 4 and 5 share the same code block, and 0 and 6 share another code block:

Example
```
switch (new Date().getDay()) {
  case 4:
  case 5:
    text = "Soon it is Weekend";
    break;
  case 0:
  case 6:
    text = "It is Weekend";
    break;
  default:
    text = "Looking forward to the Weekend";
}

- Strict Comparison
Switch cases use strict comparison (===).
The values must be of the same type to match

```
