### ISSUE TITLE
JavaScript For Loop

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/me-parissa#46]
https://www.w3schools.com/js/js_loop_for.asp

**Comment by Parissa-Parsania** [comment]
Summary:

- JavaScript Loops: Loops are handy, if you want to run the same code over and over again, each time with a different value.
Often this is the case when working with arrays

- Different Kinds of Loops
`for `- loops through a block of code a number of times
`for/in` - loops through the properties of an object
`for/of` - loops through the values of an iterable object
`while` - loops through a block of code while a specified condition is true
`do/while` - also loops through a block of code while a specified condition is true

**Comment by Parissa-Parsania** [comment]
@arashbahreini 
I have questions from the examples in **For/In Loop** and **Looping over an array.**
please let me know when we can talk about that.
