### ISSUE TITLE
JavaScript While Loop

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/me-parissa#47]
https://www.w3schools.com/js/js_loop_while.asp

**Comment by Parissa-Parsania** [comment]
Summary:

- The `while` loop loops through a block of code **as long as** a specified condition is true.

- The` Do/While` Loop
The `do/while `loop is a variant of the `while` loop. This loop will execute the code block once, before checking if the condition is true, then it will repeat the loop as long as the condition is true.

Syntax
```
do {
  // code block to be executed
}
while (condition);
```

- Comparing For and While
a` while` loop is much the same as a for `loop`, with statement 1 and statement 3 omitted.
