### ISSUE TITLE
JavaScript Scope

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/me-parissa#51]
https://www.w3schools.com/js/js_scope.asp

**Comment by Parissa-Parsania** [comment]
Summary:
Scope determines the accessibility (visibility) of variables. 
Variables defined inside a function are not accessible (visible) from outside the function.

- Local scope: Variables declared within a JavaScript function become LOCAL to the function.

- Global scope: A variable declared outside a function, becomes GLOBAL.

A global variable has the global scope: All scripts and functions on a web page can access it. 

- Automatically Global: If you assign a value to a variable that has not been declared, it will automatically become a GLOBAL variable.

- Strict Mode

- Global Variables in HTML

- The Lifetime of JavaScript Variables

- Function Arguments
